name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Configure gcloud
        run: |
          gcloud config set project YOUR_PROJECT_ID
          gcloud auth configure-docker

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME
          gcloud run deploy YOUR_SERVICE_NAME \
            --image gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME \
            --region YOUR_REGION \
            --platform managed \
            --allow-unauthenticated
